---

name: ansible-lint
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: ansible-galaxy collection install community.general ansible.posix containers.podman community.crypto
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'

...
